# Generated by Django 3.0.5 on 2020-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.TextField()),
                ('credits', models.IntegerField()),
                ('dept', models.TextField()),
                ('sbm_req', models.TextField()),
                ('sbm_econ_req', models.TextField()),
                ('sbm_math_req', models.TextField()),
                ('sbm_bba_req', models.TextField()),
                ('acct_req', models.TextField()),
                ('ecof_math_req', models.TextField()),
                ('ecof_req', models.TextField()),
                ('fina_acct_req', models.TextField()),
                ('fina_comp_req', models.TextField()),
                ('fina_req', models.TextField()),
                ('gbus_3000_req', models.TextField()),
                ('gbus_req', models.TextField()),
                ('is_comp_req', models.TextField()),
                ('is_req', models.TextField()),
                ('is_analytics_req', models.TextField()),
                ('is_audit_req', models.TextField()),
                ('mark_req', models.TextField()),
                ('mgmt_csr_req', models.TextField()),
                ('mgmt_consulting_req', models.TextField()),
                ('mgmt_entr_req', models.TextField()),
                ('mgmt_deal_req', models.TextField()),
                ('mgmt_hr_req', models.TextField()),
                ('om_option_elective_req', models.TextField()),
                ('om_option_req', models.TextField()),
                ('om_req', models.TextField()),
                ('qfin_math_a_req', models.TextField()),
                ('qfin_math_b_req', models.TextField()),
                ('qfin_electives_a_req', models.TextField()),
                ('qfin_electives_b_req', models.TextField()),
                ('qfin_electives_c_req', models.TextField()),
                ('qfin_req', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
