# Generated by Django 3.0.5 on 2020-04-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200427_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='econ_req',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
